### ISSUE TITLE
Custom selects do not update native selects

### ISSUE THREAD

**Issue by andrewcio** [CodyHouse/cd-custom-select-changelog#1]
I've noticed that when using a custom select, the related native select element is not updated. This is an issue when binding change events to the (hidden) native select element.

**Comment by claudia-romano** [comment]
Hi there, thanks for the heads-up. We just pushed an updated version that fixes the issue (a 'change' event is now emitted when a new option is selected).

Let me know if you are still having problems. Cheers!

**Comment by andrewcio** [comment]
Awesome! Works like a charm. I appreciate the quick response and solution. Thank you @claudia-romano!
