### ISSUE TITLE
Custom Icon is displayed along with the default icon

### ISSUE THREAD

**Issue by jimmck** [CodyHouse/cd-custom-select-changelog#2]
Hi,
I am learning the framework with the desire to incorporate with my Vue libraries. I wrote a quick HTML to see if I have setup  your environment. Built a style.css. And setup the HTML. The cody table component works well. I notice your sample page for this control does not show the default icon. It happens to me in every browser on my MAC.

 System Version:	macOS 10.15.4 (19E266)
  Kernel Version:	Darwin 19.4.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal
  User Name:	James McKearney (jimm)
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled
  Time since boot:	5:04

All the latest versions of Chrome and Firefox.

Here is the HTML I use to test the install...

<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="assets/cody/css/style.css">
        <script>document.getElementsByTagName("html")[0].className += " js";</script>
        <script src="assets/cody/js/util.js"></script>
        <script src="assets/cody/js/components/_custom-select.js"></script>
        <title>My Custom Select</title>
    </head>
    <body>
        <label class="form-label margin-bottom-xxxs" for="selectThis">Select:</label>
        <div class="select">
            <select class="--custom-dropdown select__input form-control" name="selectThis" id="selectThis">
                <optgroup label="Group 1">
                    <option value="0">Select option</option>
                    <option value="1">Option 1</option>
                    <option value="2">Option 2</option>
                </optgroup>
                <optgroup label="Group 2">
                    <option value="3">Option 3</option>
                    <option value="4">Option 4</option>
                    <option value="5">Option 5</option>
                </optgroup>
            </select>
            <svg class="icon select__icon" aria-hidden="true" viewBox="0 0 16 16">
                <g stroke-width="1" stroke="currentColor">
                    <polyline fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10"
                              points="15.5,4.5 8,12 0.5,4.5 "></polyline>
                </g>
            </svg>
        </div>
    </body>
</html>

Regards,
Jim

**Comment by jimmck** [comment]
Hi again,
I please note I am using the SASS directions for building my test phase. No Vue code yet. Just trying
to get an idea of the layout of your components and build process.

I am rebuilding the scss file to style.css and when I at the style.css it contains the components.

Here is a new version of the HTML for MY custom select.

Regards Jim

--------------------------------------

<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script>document.getElementsByTagName("html")[0].className += " js";</script>
        <link rel="stylesheet" href="assets/cody/css/style.css">
        <title>My Custom Select</title>
    </head>
    <body>
    <script src="assets/cody/js/util.js"></script>
    <script src="assets/cody/js/components/_custom-select.js"></script>
    <label class="form-label margin-bottom-xxxs" for="selectThis">Select:</label>
        <div class="select">
            <select class="select__input form-control" name="selectThis" id="selectThis">
                <optgroup label="Group 1">
                    <option value="0">Select option</option>
                    <option value="1">Option 1</option>
                    <option value="2">Option 2</option>
                </optgroup>
                <optgroup label="Group 2">
                    <option value="3">Option 3</option>
                    <option value="4">Option 4</option>
                    <option value="5">Option 5</option>
                </optgroup>
            </select>
            <svg class="icon select__icon" aria-hidden="true" viewBox="0 0 16 16">
                <g stroke-width="1" stroke="currentColor">
                    <polyline fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10"
                              points="15.5,4.5 8,12 0.5,4.5 "></polyline>
                </g>
            </svg>
        </div>
    </body>
</html>
------------------------------------------------------------

**Comment by jimmck** [comment]
```
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script>document.getElementsByTagName("html")[0].className += " js";</script>
        <link rel="stylesheet" href="assets/cody/css/style.css">
        <title>My Custom Select</title>
    </head>
    <body>
    <script src="assets/cody/js/util.js"></script>
    <script src="assets/cody/js/components/_custom-select.js"></script>
    <label class="form-label margin-bottom-xxxs" for="selectThis">Select:</label>
        <div class="select">
            <select class="select__input form-control" name="selectThis" id="selectThis">
                <optgroup label="Group 1">
                    <option value="0">Select option</option>
                    <option value="1">Option 1</option>
                    <option value="2">Option 2</option>
                </optgroup>
                <optgroup label="Group 2">
                    <option value="3">Option 3</option>
                    <option value="4">Option 4</option>
                    <option value="5">Option 5</option>
                </optgroup>
            </select>
            <svg class="icon select__icon" aria-hidden="true" viewBox="0 0 16 16">
                <g stroke-width="1" stroke="currentColor">
                    <polyline fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10"
                              points="15.5,4.5 8,12 0.5,4.5 "></polyline>
                </g>
            </svg>
        </div>
    </body>
</html>
```

**Comment by jimmck** [comment]
Sorry forgot to "```"

Jim

**Comment by jimmck** [comment]
Hi Again!!!
Being stuck at home is fun....
Okay so I have codekit app on my mac. I was using an old sass compiler to build css. Created a codekit
project and rebuilt the css. And voila I have the same page you guys have.

So can you you please share expected versions of sass/scss compilers?

Any tech info on your package? Expected JS/CSS.  Event handlers? JS code going to have to go into a Vue module.  Whats the difference between scripts.js and utils.js?

Having fun!!!
Jim
And Thanks!

**Comment by claudia-romano** [comment]
Hi Jim,
in CodyFrame we use CSS custom properties so it is possible the old version of codekit you had did not support those.

About JS:
- I would suggest to include it before the body closing tag (rather than inside the head element);
- The framework comes with a gulp configuration file that takes care of combining all JS files in a single one (script.js file). 
- The util.js file contains some utility functions that we use in our components; the gulp file combine this file with the other components JS files;
- We do have a tutorial on using our components with Vue:
https://codyhouse.co/blog/post/using-the-codyhouse-components-with-vue-js

You can also find some additional info about the Gulp config file on our Docs section:
https://codyhouse.co/ds/docs/framework#gulp

This should help you setting up your project! Cheers.
