### ISSUE TITLE
Update 'input' event on native select

### ISSUE THREAD

**Issue by dominicht** [CodyHouse/cd-custom-select-changelog#3]
This is related to this issue #1 

I think also adding an ["input" event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event) to the native select would be good as well on this.

**Comment by claudia-romano** [comment]
Hi there, thanks for the suggestion. We have updated the component:
https://codyhouse.co/ds/components/app/custom-select--custom-dropdown

Cheers!
